### PR TITLE
[rxxxx] - Dire Maul: North - Tribute Run

### PR DESCRIPTION
**Pull request by Tobschinski**
Due to handling via database, the Tribute Chest can be spawned infinitely. That must not be, therefore, this PR was created.
The whole event should also be closer to the original one.

What should be fixed:
- Mizzle the Crafty is now summoned, not permanently spawned even before the King is dead.
- You can no longer summon unlimited amounts of Tribute Chests, even before you engaged the King. (and after that)
- Cho'Rush and Captain Kromcrush will properly reset now if you kill the King. (Faction + Evade)
- The King Gordok Buff lasts as long as you stay inside the dungeon, you do no longer need to die to get rid of it. (-> multiple runs)

### CODE REVIEW

**Comment by Schmoozerd** [comment]
these ids are official data and one must "know" them to be able to use them :(

**Comment by xfurry** [comment]
As far as I know, this event is already working fine. 
Why is this script required?

**Comment by Tobschinski** [comment]
> As far as I know, this event is already working fine. 

I do not know the other versions, but the classic one is not even close the the event on retail, sadly. And there is more in here than just the chest-handling.

Currently, you can spawn as many chests as you want to do, get infinite amounts of items. That's bad, even if the King is still alive.
There is no faction update at all if the King dies. (Cho'Rush and Kromcrush need one)
The Gordok Buff will never run out.

**Comment by xfurry** [comment]
I remember that I personally finished this event some time ago: https://github.com/scriptdev2/scriptdev2/commit/d3d57a33
and I know that the chest spawn and gossips are already in UDB and it shouldn't be possible to spawn the chest multiple times.
Also the Buff will disappear outside the instance and the faction update is done on player not on npcs, using the aura - http://www.wowhead.com/spell=22799

The only possible missing part would be a linking flag: FLAG_EVADE_ON_DEATH to force all npcs to evade on king death.

So let me do a review of the whole event using SD2 master and UDB and I will get back to you later.
(next week, because I'm still in holiday now :smile: )

**Comment by Tobschinski** [comment]
Enjoy your time! :)

> I know that the chest spawn and gossips are already in UDB and it shouldn't be possible to spawn the chest multiple times. 
How would that be possible via DB?

> Also the Buff will disappear outside the instance and the faction update is done on player not on npcs, using the aura - http://www.wowhead.com/spell=22799
This is correct for NPCs having the Faction 45. However, Kromcrush does not have that faction, as he is also involved in the Ogre Suit Event. Cho'Rush needs a faction update as soon as the King dies, because the player does not have the buff at that point.
The buff will not be removed on the classic core, it lasts days.

The whole commit is based on sniffs, not my own thoughts. That should be mentioned as well : /

**Comment by cala** [comment]
I link this PR to this issue: https://github.com/scriptdev2/scriptdev2-classic/issues/5 because everything related to DB is now fixed in Classic DB (or ACID). The only remaining issues are the one described in this PR. So once they are fixed, the issue can also be closed.

**Comment by xfurry** [comment]
@cala I already discussed this with the author and there might be additional changes to the DB. Will catch up with you soon.

**Comment by cala** [comment]
Nice. :)
Enjoy your holidays!

**Comment by xfurry** [comment]
I think we should look in details at this vid: https://www.youtube.com/watch?v=yFAEbbo3VlA and redo the whole event based on these details.

It looks that not everything that you provided in this PR is correct.
Moreover you should try not to use hacks like this: https://github.com/Tobschinski/scriptdev2/commit/b306cb4fdabb7ca353d967c190c5e9a05956e6c7#diff-362b0da4c1527db0bc4102edd3eaa223R53

One more thing that we need to consider: how do we fix the doors? Currently all the doors in the North side are not selectable / usable. I think they should be usable somehow, so I'm not sure how is the GO flag handled.

**Comment by xfurry** [comment]
So far I have this for SD2:

```diff
diff --git a/scripts/kalimdor/dire_maul/dire_maul.h b/scripts/kalimdor/dire_maul/dire_maul.h
index 696e61d..e4e17bd 100644
--- a/scripts/kalimdor/dire_maul/dire_maul.h
+++ b/scripts/kalimdor/dire_maul/dire_maul.h
@@ -75,15 +75,20 @@ enum
     GO_KNOTS_BALL_AND_CHAIN     = 179511,
     GO_GORDOK_TRIBUTE           = 179564,
     GO_NORTH_LIBRARY_DOOR       = 179549,
+    GO_GORDOK_COURTYARD_DOOR    = 177219,
+    GO_GORDOK_INNER_DOOR        = 177217,
 
     SAY_FREE_IMMOLTHAR          = -1429000,
     SAY_KILL_IMMOLTHAR          = -1429001,
     SAY_IRONBARK_REDEEM         = -1429002,
+    SAY_CHORUSH_KING_DEAD       = -1429003,
 
     FACTION_HOSTILE             = 14,
-    SPELL_KING_OF_GORDOK        = 22799,
+    FACTION_FRIENDLY            = 35,
 };
 
+static const float afMizzleSpawnLoc[4] = {683.296f, 484.384f, 29.544f, 0.0174f};
+
 class instance_dire_maul : public ScriptedInstance
 {
     public:
diff --git a/scripts/kalimdor/dire_maul/instance_dire_maul.cpp b/scripts/kalimdor/dire_maul/instance_dire_maul.cpp
index 5f66bc3..40a3b2f 100644
--- a/scripts/kalimdor/dire_maul/instance_dire_maul.cpp
+++ b/scripts/kalimdor/dire_maul/instance_dire_maul.cpp
@@ -76,6 +76,10 @@ void instance_dire_maul::OnCreatureCreate(Creature* pCreature)
         case NPC_CHORUSH:
         case NPC_KING_GORDOK:
         case NPC_MIZZLE_THE_CRAFTY:
+        case NPC_GUARD_MOLDAR:
+        case NPC_GUARD_FENGUS:
+        case NPC_GUARD_SLIPKIK:
+        case NPC_CAPTAIN_KROMCRUSH:
             break;
 
         default:
@@ -243,12 +247,29 @@ void instance_dire_maul::SetData(uint32 uiType, uint32 uiData)
             m_auiEncounter[uiType] = uiData;
             if (uiData == DONE)
             {
-                // Apply Aura to players in the map
-                Map::PlayerList const& players = instance->GetPlayers();
-                for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
+                // change faction to certian ogres
+                if (Creature* pOgre = GetSingleCreatureFromStorage(NPC_GUARD_MOLDAR))
+                    pOgre->setFaction(FACTION_FRIENDLY);
+                if (Creature* pOgre = GetSingleCreatureFromStorage(NPC_GUARD_FENGUS))
+                    pOgre->setFaction(FACTION_FRIENDLY);
+                if (Creature* pOgre = GetSingleCreatureFromStorage(NPC_GUARD_SLIPKIK))
+                    pOgre->setFaction(FACTION_FRIENDLY);
+                if (Creature* pOgre = GetSingleCreatureFromStorage(NPC_CAPTAIN_KROMCRUSH))
+                    pOgre->setFaction(FACTION_FRIENDLY);
+
+                // yell and spawn Mizzle
+                if (Creature* pOgre = GetSingleCreatureFromStorage(NPC_CHORUSH))
                 {
-                    if (Player* pPlayer = itr->getSource())
-                        pPlayer->CastSpell(pPlayer, SPELL_KING_OF_GORDOK, true);
+                    if (pOgre->isAlive())
+                        DoScriptText(SAY_CHORUSH_KING_DEAD, pOgre);
+
+                    // start WP movement; event handled by dbscripts
+                    if(Creature* pMizzle = pOgre->SummonCreature(NPC_MIZZLE_THE_CRAFTY, afMizzleSpawnLoc[0], afMizzleSpawnLoc[1], afMizzleSpawnLoc[2], afMizzleSpawnLoc[3], TEMPSUMMON_DEAD_DESPAWN, 0, true))
+                    {
+                        pMizzle->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
+                        pMizzle->SetWalk(false);
+                        pMizzle->GetMotionMaster()->MoveWaypoint();
+                    }
                 }
             }
             break;
diff --git a/sql/scriptdev2_script_full.sql b/sql/scriptdev2_script_full.sql
index e6b956c..37b63c0 100644
--- a/sql/scriptdev2_script_full.sql
+++ b/sql/scriptdev2_script_full.sql
@@ -1726,7 +1726,9 @@ INSERT INTO script_texts (entry,content_default,sound,type,language,emote,commen
 (-1429000,'The demon is loose! Quickly we must restrain him!',0,6,0,0,'highborne summoner SAY_FREE_IMMOLTHAR'),
 (-1429001,'Who dares disrupt the sanctity of Eldre\'Thalas? Face me, cowards!',0,6,0,0,'prince tortheldrin SAY_KILL_IMMOLTHAR'),
 
-(-1429002,'At last... Freed from his cursed grasp!',0,6,0,0,'old ironbark SAY_IRONBARK_REDEEM');
+(-1429002,'At last... Freed from his cursed grasp!',0,6,0,0,'old ironbark SAY_IRONBARK_REDEEM'),
+
+(-1429003,'The king is dead - OH NOES! Summon Mizzle da Crafty! He knows what to do next!',0,1,0,0,'cho\'rush SAY_KING_DEAD');
 
 -- -1 469 000 BLACKWING LAIR
 INSERT INTO script_texts (entry,content_default,sound,type,language,emote,comment) VALUES

```

I will work out the DBscript part tomorrow.
It seems there are many things messed up in this instance...

**Comment by Tobschinski** [comment]
> It looks that not everything that you provided in this PR is correct.
What is incorrect?

> One more thing that we need to consider: how do we fix the doors? Currently all the doors in the North side are not selectable / usable. I think they should be usable somehow, so I'm not sure how is the GO flag handled.
There is no interaction with SD2 needed. If you managed to kill the king, you have already opened all doors. I assume you're doing this on WotLK, because you can fully interact with the doors on Classic.

Also, there is no faction update on the guards, just on Kromcrush and Cho'rush. The guards have faction 45, like the other ogres and will be friendly if you have the buff from Mizzle.

**Comment by xfurry** [comment]
@Tobschinski please check PM on forum. It looks that classic db and udb don't match.
I'm not sure from where did UDB get the Dire Maul data, but there are many things which are for sure wrong.

So, I need to make sure I'm providing the full SD2 and DB update for all DBs in order to ensure that this event works fine.

**Comment by Schmoozerd** [comment]
@xfurry SetFactionTemporary is probably the correct choice instead of setFaction

DM-Doors:
Forget Sniffs in this case, forget current data unfortunately.
some of the doors i mentioned here: https://github.com/scriptdev2/scriptdev2/commit/8a057604e22147b7a97e18ce97d02628ff1c92a0#commitcomment-2202217

Infact i - at the moment - strongly suggest to set the DM-doors entirely on SD2 side, as the DBs will import crappy data when they import sniffs.

**Comment by xfurry** [comment]
Ok, but we need to understand the logic.
How to setup the right flags for the doors in the North side. Currently they have some not selectable flag, which makes this wing impossible to access.

Sniff might be required, at least for fine details, like creature movement and npc factions.

Overall I think that the whole Dire Maul instance should be rechecked and possibly rebuild and respawned from scratch on the DB side.
There are a lot of broken npc flags, broken go flags, missing movements, duplicate spawns... 
Currently I don't trust any DB provider for this instance because neither UDB nor Classic DB proved that they have the right data that will match with what I can see in vids.

**Comment by Schmoozerd** [comment]
ok, i just checked.
```
UPDATE gameobject_template SET flags=34 WHERE entry IN (177217,177219);
```
Udb just had crap data.

**Comment by cala** [comment]
>  It looks that classic db and udb don't match

That is true. Two years ago, the data were mostly the same as DM in Classic DB was basically a copy of UDB data which are not very good (for this dungeon, I mean). Since, @Tobschinski @evil-at-wow and myself fixed many things, hence the differences.

The eastern part of the dungeon was fully remade by @evil-at-wow based on sniffs from 3.x.x and is nearly retail-like now. But Northern and Western part are still in bad shapes yet things are slowly improving, especially for the Northern part.

But I can understand that DM:North is a complex dungeon to script and that further changes (or even reversals) may be needed along with the SD2 changes currently discussed here.

**Comment by evil-at-wow** [comment]
> Overall I think that the whole Dire Maul instance should be (...) rebuild and respawned from scratch on the DB side.

I fully agree, so [I am doing exactly that](https://github.com/evil-at-wow/TBC-DB-development/commits/master) (I wouldn't add this to UDB just yet though, it needs a few extra tweaks first).

> The eastern part of the dungeon was fully remade by @evil-at-wow based on sniffs from 3.x.x and is nearly retail-like now. 

Just to avoid any confusion: I respawned all *creatures* from scratch (excluding most critters), including their movement and pooling. Nothing more and nothing less. I didn't change anything for gameobjects, gossip, factions, etc, so if anything is fixed in that area, it wasn't me!

> But Northern and Western part are still in bad shapes.

Have patience young grasshopper! I promised to respawn the West and North wings too to make them (near) perfect, and I still intent to keep that promise. West is in progress, but I ran into core issues I want to fix first (I refuse to do an inferior job by working around the issues). I know I move very slowly because of a lack of time, but rest assured my determination is unequaled!

**Pull request closed without merging**
