### PR TITLE
Removing npc_professions.cpp as specializations were not unlearnable in ...

### PR DESCRIPTION
**Pull request by Sinoxan**
...classic.

* If you wanted to change specialization you had to unlearn the entire profession and start over again.

### CODE REVIEW

**Comment by xfurry** [comment]
Guys,
Please provide feedback, so we can close this.

Poke @cala and @Tobschinski again.

**Comment by Tobschinski** [comment]
This is a comment I got from thottbot.com

> You cannot make the switch once you have completed the quest for Armorsmith or Weaponsmith...if you have not completed any leg of the quest then you can abandon it and talk to the other guy in IF or Ogrimmar.  If you have already completed any step of either quest, then you are stuck. (even if you unlearn and retrain it is locked).  Sorry to give you bad news.

**Comment by Sinoxan** [comment]
It needs editing instead of removing, I know now pretty much how it should work and I should be able to correct it I think, not very experienced with ScriptDev though.  So I'll close this now as this request is obsolete.

**Comment by Schmoozerd** [comment]
it might even be considered to implement this functionality with db-only tools.
(possible a new SCRIPT_COMMAND_UNLEARN_PROFESSION or similar will be required then though)

**Pull request closed without merging**
